services:
  - type: web
    name: shot-sync-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: shotsyncbasketball@gmail.com
      - key: BREVO_SENDER_NAME
        value: Shot Sync
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-2
      - key: FROM_EMAIL
        value: shotsyncbasketball@gmail.com

